<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher currency switcher-currency" id="switcher-currency<?php echo $id?>">
    <!--strong class="label switcher-label"><span></span></strong-->
    <div class="actions dropdown options switcher-options">
        <span style="display: block;" class="action toggle switcher-trigger" id="switcher-currency-trigger<?php echo $id?>">
            <span class="language-<?php echo $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                <span><span class="hidden-xs hidden-sm"><?php echo __('Currency: ') ?></span><?php echo $block->escapeHtml($currentCurrencyCode) ?><i class="fa fa-angle-down"></i></span>
            </span>
        </span>

        <ul class="dropdown switcher-dropdown" style="display:none;" data-mage-init='{"dropdownDialog":{
            "appendTo":"#switcher-currency<?php echo $id?> > .options",
            "triggerTarget":"#switcher-currency-trigger<?php echo $id?>",
            "closeOnMouseLeave": false,
            "triggerClass":"active",
            "parentClass":"active",
            "defaultDialogClass":"dropdown-menu",
            "buttons":null}}'>
            <?php foreach ($currencies as $_code => $_name): ?>
                <?php if ($_code != $currentCurrencyCode): ?>
                    <li class="currency-<?php echo $_code ?> switcher-option">
                        <a href="#" data-post='<?php echo $block->getSwitchCurrencyPostData($_code); ?>'><?php echo $_code ?> - <?php echo $_name ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
