<?php
	$themeHelper = $this->helper('MGS\Social\Helper\Data');
	$access_token = $themeHelper->getAccessToken(); 
	$number = $themeHelper->getNumber(); 
	$width = $themeHelper->getWidth();
	$height = $themeHelper->getHeight();
?>
<?php if($themeHelper->getEnable() && $access_token && $number): ?>
	<div class="block-content">
		<?php $block->getInstagramData($access_token,$number, $width, $height); ?>
	</div> 
<?php else: ?>
	<p><?php echo __('The instagram extension had disabled or no "User Name" or no "Client ID" or no "Number of Images want to show" ') ?></p>
<?php endif; ?>
