<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="block account-nav panel panel-default">
    <div class="panel-heading block-title">
        <h4 class="title"><span><?php /* @escapeNotVerified */ echo __('My Account'); ?></span></h3>
    </div>
    <div class="panel-body">
        <nav class="account-nav">
            <ul class="nav items">
                <?php echo $block->getChildHtml();?>
            </ul>
        </nav>
    </div>
</div>
