<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="footer-container footer-v2">
    <section class="middle-footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 middle-block">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('molly_ft_about')->toHtml() ?>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 middle-block">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('molly_ft_contacts')->toHtml();?>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 middle-block">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('molly_ft_info')->toHtml();?>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 middle-block">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('molly_ft_instagram')->toHtml();?>
				</div>
				
			</div>
		</div>
    </section>
    <section class="bottom-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
				</div>
            </div>
        </div>
    </section>
</div>
