<?php $block = $this->getBlock() ?>
<?php $welcomeMessage = $block->getWelcome(); ?>
<div class="header-v2">
<div class="top-header-content">
	<div class="top-header-wraning-tips">WARNING: This product contains nicotine. Nicotine is an addictive chemical.</div>

	<div class="container">
		<div class="row ">
			<div class="col-lg-4 col-md-4 col-sm-8 col-xs-12 top-bar-left pull-left">
				<div class="header-freeshipping-tips">
					<span>FREE DOMESTIC U.S. SHIPPING ABOVE $50</span>
					<span class="welcome-title" data-bind="text: '<?php echo $block->escapeHtml($welcomeMessage) ?>'">
						<?php echo $block->escapeHtml($welcomeMessage) ?>
					</span>
				</div>
			</div>
			<div class="col-lg-8 col-md-8 col-sm-4 col-xs-12 top-bar-right pull-right">
				<div class="header-account">
					<?php echo $block->getChildHtml('store_language') ?>
					<?php echo $block->getChildHtml('currency') ?>
                    <?php echo $block->getChildHtml('minicart') ?>
					<div class="switcher top-links" id="top-links">
						<span class="name" data-mage-init='{"dropdown":{}}' data-toggle="dropdown">
								<span><i class="user-icon icon"></i></span>
						</span>
						<ul class="menu dropdown switcher-dropdown ui-dialog-content" data-target="dropdown" style="display:none;" data-mage-init='{"dropdownDialog":{
								"appendTo":"#top-links",
								"triggerTarget":"#top-links > .name",
								"closeOnMouseLeave": false,
								"triggerClass":"active",
								"parentClass":"active",
								"defaultDialogClass":"dropdown-menu",
								"buttons":null}}'>
							<?php echo $block->getChildHtml('top.links') ?>
						</ul>
					</div>

					<?php echo $block->getChildHtml('topSearch') ?>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="logo-container">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<?php echo $block->getChildHtml('logo') ?>
			</div>
		</div>
	</div>
</div>
<div class="middle-header-content navbar-collapse">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<button class="btn btn-responsive-nav btn-inverse"> <em class="fa fa-bars">&nbsp;</em> </button>
				<?php echo $block->getChildHtml('mgs-megamenu') ?>
			</div>
		</div>
	</div>
</div>
</div>