<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search pull-right switcher" id="topsearch-dropdown">
    <span class="name" data-mage-init='{"dropdown":{}}' data-toggle="dropdown">
        <span class="action"><i class="fa fa-search"></i></span>
    </span>
    <div class="block block-content dropdown switcher-dropdown" style="display:none;" data-target="dropdown" data-mage-init='{"dropdownDialog":{
            "appendTo":"#topsearch-dropdown",
            "triggerTarget":"#topsearch-dropdown > .name",
            "closeOnMouseLeave": false,
            "triggerClass":"active",
            "parentClass":"active",
            "defaultDialogClass":"dropdown-menu",
            "buttons":null}}'>
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
			<div class="form-group">
				<input id="search"
					   data-mage-init='{"quickSearch":{
							"formSelector":"#search_mini_form",
							"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest'); ?>",
							"destinationSelector":"#search_autocomplete"}
					   }'
					   type="text"
					   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
					   value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
					   placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
					   class="input-text form-control"
					   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
					   role="combobox"
					   aria-haspopup="false"
					   aria-autocomplete="both"
					   autocomplete="off"/>
				<button type="submit" title="<?php echo $block->escapeHtml(__('Search')) ?>" class="btn btn-primary">
					<em class="fa fa-search"></em>
				</button>	   
				<div id="search_autocomplete" class="search-autocomplete"></div>
				<?php echo $block->getChildHtml() ?>
			</div>
        </form>
    </div>
</div>
