
<?php $_storeView = $this->getStoreView(); ?>

    <div class="row store-details storelocator-details">
        <div class="col-md-5 col-sm-12 col-xs-12">
            <div class="page-title">
                <h1><?php echo $this->escapeHtml($_storeView->getName()) ?></h1>
            </div>
            <?php if ($imageUrl = $_storeView->getImageUrl()): ?>
                <div class="store-image">
                    <img src="<?php echo $imageUrl ?>" alt="<?php echo $_storeView->getName() ?>" title="<?php echo $_storeView->getName() ?>" class="img-responsive"/>
                </div>
            <?php endif ?>
            <div class="store-info-detail">
				<div class="store-html-content store-information">
					<h3><?php echo __('Store Information') ?></h3>
					<div class="content responsive-table">
						<table class="table portfolio-table table-hover">
							<tbody>
								<tr>
									<td><?php echo __('Address') ?>:</td>
									<td><?php echo $_storeView->getStreetAddress().' '.ucfirst($_storeView->getCity()).' '.ucfirst($_storeView->getState()).' '.$_storeView->getZipcode().' '.$_storeView->getCountry() ?></td>
								</tr>
								<?php if($_storeView->getPhone()): ?>
									<tr>
										<td><?php echo __('Phone:') ?></td>
										<td><a href="tel:<?php echo $this->escapeHtml($_storeView->getPhone()) ?>"><?php echo $this->escapeHtml($_storeView->getPhone()) ?></a></td>
									</tr>
								<?php endif; ?>
								<?php if($_storeView->getEmail()): ?>
									<tr>
										<td><?php echo __('Email:') ?></td>
										<td><a href="mailto:<?php echo $this->escapeHtml($_storeView->getEmail()) ?>"><?php echo $this->escapeHtml($_storeView->getEmail()) ?></a></td>
									</tr>
								<?php endif; ?>
								<?php if($_storeView->getFax()): ?>
									<tr>
										<td><?php echo __('Fax:') ?></td>
										<td><?php echo $this->escapeHtml($_storeView->getFax()) ?></td>
									</tr>
								<?php endif; ?>
								<?php if($_storeView->getPhoneNumber()): ?>
									<tr>
										<td><?php echo __('Phone:') ?></td>
										<td><?php echo $this->escapeHtml($_storeView->getPhoneNumber()) ?></td>
									</tr>
								<?php endif; ?>
								<?php if($_storeView->getWebsite()): ?>
									<tr>
										<td><?php echo __('Website:') ?></td>
										<td><a href="<?php echo $_storeView->getWebsite() ?>"><?php echo $_storeView->getWebsite() ?></a></td>
									</tr>
								<?php endif; ?>
							</tbody>
						</table>
					</div>
				</div>
                <?php if($_storeView->getDescription()): ?>
                    <div class="store-html-content store-description">
                        <h3><?php echo __('Store Information') ?></h3>
                        <div class="content">
                            <?php echo $this->getDescription(); ?>
                        </div>
                    </div>
                <?php endif ?>

                <?php if($_storeView->getTradingHours()): ?>
                    <div class="store-html-content store-opening-hours">
                        <h3><?php echo __('Opening Hours') ?></h3>
                        <div class="content">
                            <?php echo $this->getTradingHours(); ?>
                        </div>
                    </div>
                <?php endif ?>
            </div>
        </div>
        <div class="col-md-7 col-sm-12 col-xs-12">
            <div id="map-detail"></div>
            <p class="back">
                <a href="<?php echo $block->getUrl('locator/') ?>" title="<?php echo __('Back') ?>">
                    <span><i class="fa fa-angle-double-left" style="margin-right: 10px;"></i><?php echo __('Back') ?></span>
                </a>
            </p>
        </div>
    </div>
<?php
//Get store google map related information
$storeName = $_storeView->getName();
$storeLat = $_storeView->getLat();
$storeLong = $_storeView->getLng();
$storeRadius = $this->getRadius($_storeView);
?>
<?php if($storeLat && $storeLong): ?>
    <script>
        require(['jquery', 'MGS_StoreLocator/js/storelocator'], function($) {
            $(window).load(function() {
                var storeLat = <?php echo $storeLat ;?>;
                var storeLong = <?php echo $storeLong ;?>;
                var storeRadius = <?php echo $storeRadius ;?>;
                var storeInfoText = '<div class="map-short-info"><h3><?php echo $storeName ; ?></h3><p><?php echo $_storeView->getStreetAddress() ?> <?php echo $_storeView->getCity() ?> <?php echo $_storeView->getState() ?> <?php echo $_storeView->getZipcode() ?> <?php echo $_storeView->getCountry() ?></p>';
                var googleMapDivId = 'map-detail';
                google.maps.event.addDomListener(window, 'load', initializeMap(storeLat, storeLong, storeRadius, storeInfoText, googleMapDivId));
            });
        });
    </script>
<?php endif ?>