<?php $products = $this->getProductCollection() ?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings(); 
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$image_sm = 'category_page_grid'; ?>
<?php $customClass = $this->getCustomClass() ?>
<div class="sidebar_deal <?php if($customClass): ?><?php echo $customClass ?><?php endif ?>">
	<div class="slider-deal">
		<div class="title-block">
			<h4 class="title">
				<?php if($this->hasData('title')): ?>
					<span><?php echo $this->getData('title') ?></span>
				<?php else: ?>
					<span><?php echo __('Hot Deal Every Day'); ?></span>
				<?php endif ?>
			</h4>
		</div>
		<?php if(count($products)>0): ?>
			<div id="deal_products">
				<?php foreach($products as $_product): ?>
					<div class="item">
						<div class="product-content">
							<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
							<?php 	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
									$size = $themeHelper->getImageSize();
									$productImage = $_imagehelper->init($_product, $image_sm)->resize($size['width'], $size['height'])->getUrl();
									?>
							<div class="product-top">
								<div class="discount-save">
									<div class="save-content">
										<div class="percent">
											<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
											<?php $percent = round(($save*100)/$_product->getPrice(), 1) ?>
											<?php echo $percent ?>%
										</div>
									</div>
								</div>
								<a href="<?php echo $_product->getProductUrl() ?>" class="product-image">
									<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive"/>
								</a>
							</div>
							<div class="product-desc">
								<div class="top-desc">
									<div class="text-desc cate-name no-cp">
										<div class="text">
											<span><?php echo __('Hot Deals') ?></span>
										</div>
									</div>
									<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
										<ul class="icon-links">
											<li class="wl-item">
												<a href="#" data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'  class="action towishlist <?php if(!$themeHelper->checkInWishilist($_product->getId())): ?>no-active<?php endif ?>" data-action="add-to-wishlist" title="<?php echo __('Add to Wish List') ?>">
													<i class="fa <?php if($themeHelper->checkInWishilist($_product->getId())): ?>fa-heart active<?php else: ?>fa-heart-o<?php endif ?>"></i>
												</a>
											</li>
										</ul>
									<?php endif; ?>
								</div>
								<p class="product-name">
									<strong><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_product->getName() ?></a></strong>
								</p>
								<div class="desc-prd">
									<div class="information-prd">
										<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product); ?>
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
									</div>
									<div class="add-cart-item">
										<div class="product-item-actions">
											<div class="actions-primary">
												<?php if ($_product->isSaleable()): ?>
													<?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
														<button class="btn btn-primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_product) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
														</button>
													<?php else: ?>
														<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
														?>
														<button class="btn btn-primary btn-lg"
																data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
															<span><?php /* @escapeNotVerified */ echo __('Buy Now') ?></span>
														</button>
													<?php endif; ?>
												<?php else: ?>
													<?php if ($_product->getIsSalable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif; ?>
												<?php endif; ?>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="slide-deals">
								<?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml() ?>
								<div class="clear"></div>
							</div>
						</div>
					</div>
				<?php endforeach ?>
			</div>
			<script type="text/javascript">
				require([
					'jquery',
					'MGS_Mpanel/js/owl.carousel.min'
				], function(jQuery){
					(function($) {
						$("#deal_products").owlCarousel({
							items: 1,
							nav: false,
							loop: true,
							navText: ["<i class='fa fa-angle-left'	></i>","<i class='fa fa-angle-right'></i>"],
							dots: false,
							autoplay: true,
							responsive:{
								0 : {items: 1},
								480 : {items: 1},
								768 : {items: 2},
								980 : {items: 1},
								1200 : {items: 1}
							}
						});
					})(jQuery);
				});
			</script>
		<?php else: ?>
			<div class="message info empty"><div><?php echo __('We can\'t find deals matching the selection.') ?></div></div>
		<?php endif ?>
	</div>
</div>