<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php
$_itemCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'category_page_grid';
	$imageTwo = 'category_page_two_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false; 
?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title):?>
        <div class="block-title col-md-12 col-sm-12 col-xs-12">
            <h3><?php /* @escapeNotVerified */ echo $title; ?></h3>
        </div>
        <?php endif ?>
        <div class="block-content col-md-12 col-sm-12 col-xs-12">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="row products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item '. $themeHelper->getColClass($themeSettings['catalog']['per_row']) .'">' : '</li><li class="item product product-item '. $themeHelper->getColClass($themeSettings['catalog']['per_row']) .'">' ?>
						<?php
							$_itemNameStripped = $block->stripTags($_item->getName(), null, true);
						?>
                        <div class="product-item-info product-content">
							<div class="product-top">
								<?php
									$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
									$size = $themeHelper->getImageSize();
									$productImage = $_imagehelper->init($_item, $image)->resize($size['width'], $size['height'])->getUrl();
								?>
								<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
									<img src="<?php echo $productImage; ?>" alt="<?php echo $_itemNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
									<?php if(basename($_item->getData('image')) !=  'no_selection'): ?>
										<?php if(basename($_item->getData('image')) != basename($_item->getData('small_image'))): ?>
											<?php $productImageTwo = $_imagehelper->init($_item, $imageTwo)->resize($size['width'], $size['height'])->getUrl(); ?>
											<img src="<?php echo $productImageTwo; ?>" alt="<?php echo $_itemNameStripped ?>" class="img-responsive img-two product-image-photo img-thumbnail"/>
										<?php endif ?>
									<?php endif ?>
								</a>
								<?php echo $themeHelper->getProductLabel($_item) ?>
							</div>
                            <div class="product-item-details details product-desc">
								<div class="top-desc">
									<?php $cats = $_item->getCategoryIds(); ?>
									<?php if(count($cats) > 0): ?>
										<?php $j=0; foreach ($cats as $category_id): $j++; ?>
											<?php if($j ==2 ){ break; } ?>
											<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
											<?php $currentCate = $objectManager->create('Magento\Catalog\Model\Category')->load($category_id); ?>
											<div class="text-desc cate-name">
												<div class="text">
													<span><?php echo $currentCate->getName(); ?></span>
												</div>
											</div>
										<?php endforeach; ?>
									<?php else: ?>
										<div class="text-desc cate-name">
											<div class="text">
												<span>&nbsp;</span>
											</div>
										</div>
									<?php endif ?>
									<div class="controls">
										<?php if(!$themeSettings['catalog']['wishlist_button'] || !$themeSettings['catalog']['compare_button']): ?>
											<?php if ($showWishlist || $showCompare): ?>
												<ul class="actions-secondary" data-role="add-to-links">
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist && !$themeSettings['catalog']['wishlist_button']): ?>
														<li><a href="#"
														   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
														   class="action <?php if(!$themeHelper->checkInWishilist($_item->getId())): ?>no-active<?php endif ?> towishlist" data-action="add-to-wishlist"
														   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
															<i class="fa <?php if($themeHelper->checkInWishilist($_item->getId())): ?>fa-heart active<?php else: ?>fa-heart-o<?php endif ?>"></i>
														</a></li>
													<?php endif; ?>
													<?php if ($block->getAddToCompareUrl() && $showCompare && !$themeSettings['catalog']['compare_button']): ?>
														<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
														<li><a href="#" class="action tocompare"
														   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
														   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
															<i class="fa fa-sliders"></i>
														</a></li>
													<?php endif; ?>
												</ul>
											<?php endif; ?>
                                        <?php endif; ?>
									</div>
								</div>
                                <p class="product name product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </p>
								<div class="desc-prd">
									<div class="information-prd">
										<?php echo $block->getProductPriceHtml($_item, $type); ?>
										<?php if ($templateType): ?>
											<?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
										<?php endif; ?>
									</div>
									<?php if ($showCart): ?>
										<div class="add-cart-item">
											<div class="product-item-actions">
												<?php if ($showCart): ?>
													<div class="actions-primary">
														<?php if ($_item->isSaleable()): ?>
															<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
																<button class="action tocart primary btn btn-primary"
																		data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																</button>
															<?php else: ?>
																<?php
																	$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
																	$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
																?>
																<button class="action tocart primary btn btn-primary"
																		data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
																		type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
																	<span><span class="fa fa-shopping-cart"></span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
																</button>
															<?php endif; ?>
														<?php else: ?>
															<?php if ($_item->getIsSalable()): ?>
																<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
															<?php else: ?>
																<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
															<?php endif; ?>
														<?php endif; ?>
													</div>
												<?php endif; ?>
											</div>
										</div>
									<?php endif; ?>
								</div>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
