<?php
$helper = $this->helper('MGS\Blog\Helper\Data');
$collection = $block->getPostCollection();
?>
<?php if (count($collection)): ?>
	<?php 	$blockId = rand() . time();
			$title = $this->getConfig('title');
			$numberOfPosts = $this->getConfig('number_of_posts');
			$showThumbnail = $this->getConfig('show_thumbnail');
			$width = $this->getConfig('thumbnail_width', 240);
			$height = $this->getConfig('thumbnail_height', 180);
			$showShortContent = $this->getConfig('show_short_content');
			$viewAs = $this->getConfig('view_as');
			$customClass = $this->getConfig('custom_class'); ?>
		<?php if ($title): ?>
			<div class="title-center">
				<h3 class="heading"><span><?php echo $title ?></span></h3>
			</div>
		<?php endif ?>
		<div class="widget-latest-post <?php echo $customClass ?>">
			<div class="row">
				<div id="latest-post-carousel" class="latest-post <?php if ($viewAs == 'owl_carousel'): ?> owl-carousel latest-post-carousel owl-theme<?php endif ?>">
					<?php foreach ($collection as $post): ?>
					<div class="item blog-view-container <?php if ($viewAs == 'default'): ?>col-md-6 col-sm-6 col-xs-12<?php endif ?>">
						<div class="latest-post-img">
							<a class="blog_link_img" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getPostUrlWithNoCategory(); ?>">
								<img class="img-responsive" src="<?php echo $post->getThumbnailUrl(); ?>" alt="<?php echo $post->getTitle(); ?>"/>
							</a>
							<a class="read-more" title="<?php echo __('Read More'); ?>" href="<?php echo $post->getPostUrlWithNoCategory(); ?>"><span class="fa fa-search">&nbsp;</span><?php echo __('Read More'); ?></a>
							<div class="day-desc">
								<span class="day"><?php echo date('d', strtotime($post->getCreatedAt())) ?></span>
								<span class="month"><?php echo date('M', strtotime($post->getCreatedAt())) ?></span>
							</div>
						</div>
						<div class="latest-post-decs">
							<div class="latest-name">
								<a href="<?php echo $post->getPostUrlWithNoCategory(); ?>" title="<?php echo $post->getTitle(); ?>"><?php echo $post->getTitle() ?></a>
							</div>
							<div class="latest-date">
								<div class="post-info text-desc">
									<span class="user-author"><?php  if ($post->getUpdatedByUser()){ $author = $post->getUpdatedByUser();
											}else { $author = $post->getUser(); } ?><?php echo $author ?></span>
									<span>
										<?php if ($helper->getConfig('comment_settings/enabled')): ?>
											<?php $many = ''; ?>
											<?php if($post->getCommentCount() > 1){ $many = 's'; } ?>
												<a href="<?php echo $post->getPostUrlWithNoCategory(); ?>#comment-box" class="comments"><?php echo __('%1 Comment%2', $post->getCommentCount(),$many) ?></a>
										<?php endif; ?>
									</span>
								</div>
							</div>
							<?php if ($showShortContent): ?>
								<p class="short-content">
									<?php echo substr($post->getShortContent(), 0, $this->getConfig('limit_characters_short_content')); ?>
								</p>
                            <?php endif ?>
						</div>
					</div>
					<?php endforeach ?>
				</div>
			</div>
		</div>
	<?php if($viewAs == 'owl_carousel'): ?>
		<?php
			if ($this->getConfig('autoplay')) { $autoplay = 'true'; } else { $autoplay = 'false'; }
			if ($this->getConfig('stop_on_hover')) { $stopOnHover = 'true'; } else { $stopOnHover = 'false'; }
			if ($this->getConfig('navigation')) { $navigation = 'true'; } else { $navigation = 'false'; }
		?>
		<script type="text/javascript">
            require([
                'jquery',
                'mgs/owlcarousel'
            ], function ($) {
                var owl = $('#latest-post-carousel');
                owl.owlCarousel({
                    items: <?php echo $this->getConfig('items', 5); ?>,
                    autoPlay: <?php echo $autoplay; ?>,
                    stopOnHover: <?php echo $stopOnHover; ?>,
                    nav: <?php echo $navigation; ?>,
					navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
					dots: false,
					responsive:{ 0 : {items: 1}, 480 : {items: 1}, 768 : {items: 2}, 991 : {items: 2}, 1200 : {items: <?php echo $this->getConfig('items', 5); ?>} }
                });
            });
        </script>
	<?php endif ?>
<?php endif; ?>

