<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php if($themeHelper->getStoreConfig('mgstheme/general/sticky_menu')): ?>
	<script type="text/javascript">
		require([
			'jquery'
		], function(jQuery){
			(function($) {
				$(window).scroll(function () {
					if ($(this).scrollTop() > 40 && $(this).width() >= 992) {
						$('.header').addClass('header-sticky-menu');
					} else {
						$('.header').removeClass('header-sticky-menu');
					}
				});
			})(jQuery);
		});
	</script>
<?php endif ?>
<?php if($themeHelper->getStoreConfig('mgstheme/general/back_to_top')): ?>
	<a href="" class="scroll-to-top"><i class="fa fa-arrow-up"></i></a>
	<script type="text/javascript">
		require([
			'jquery'
			/* 'mgs/waypoints',
			'mgs/counterup' */
		], function(jQuery){
			(function($) {
				$(window).scroll(function(){
					if ($(this).scrollTop() > 1) {
						$('.scroll-to-top').css({bottom:"25px"});
					} else {
						$('.scroll-to-top').css({bottom:"-100px"});
					}
				});

				$('.scroll-to-top').click(function(){
					$('html, body').animate({scrollTop: '0px'}, 800);
					return false;
				});
				/* if($('body').find('counter')) {
					$('.counter').counterUp({
						delay: 20,
						time: 700
					});
				} */
			})(jQuery);
		});
	</script>
<?php endif ?>