<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/* @var $block \Magento\Framework\View\Element\Template */
?>
<div class="block block-compare panel panel-primary" data-bind="scope: 'compareProducts'" data-role="compare-products-sidebar">
    <div class="panel-heading block-title">
        <h4 id="block-compare-heading" class="title" role="heading" aria-level="2"><span><?php /* @escapeNotVerified */ echo __('Compare Products') ?> <small class="counter qty no-display" data-bind="text: compareProducts().countCaption, css: {'no-display': !compareProducts().count}"></small></span></h4>
    </div>
    <!-- ko if: compareProducts().count -->
    <div class="block-content no-display panel-body" aria-labelledby="block-compare-heading" data-bind="css: {'no-display': !compareProducts().count}">
        <ol id="compare-items" class="product-items product-items-names" data-bind="foreach: compareProducts().items">
                <li class="product-item">
                    <input type="hidden" class="compare-item-id" data-bind="value: id"/>
                    <span class="product-item-name">
                        <a data-bind="attr: {href: product_url}, html: name" class="product-item-link"></a>
                    </span>
                    <a href="#" data-bind="attr: {'data-post': remove_url}" title="<?php /* @escapeNotVerified */ echo __('Remove This Item') ?>" class="action delete pull-right">
                        <span class="fa fa-trash-o"></span>
                    </a>
                </li>
        </ol>
        <div class="actions-toolbar">
            <div class="secondary">
                <a id="compare-clear-all" href="#" class="action clear" data-post="<?=$block->escapeHtml(
                    $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataClearList()
                ) ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span>
                </a>
            </div>
            <div class="primary">
                <a data-bind="attr: {'href': compareProducts().listUrl}" class="action compare btn btn-primary btn-lg primary"><span><?php /* @escapeNotVerified */ echo __('Compare') ?></span></a>
            </div>
        </div>
    </div>
    <!-- /ko -->
    <!-- ko ifnot: compareProducts().count -->
    <div class="alert alert-warning text-center"><?php /* @escapeNotVerified */ echo __('You have no items to compare.') ?></div>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
{"[data-role=compare-products-sidebar]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script>
