<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Send to friend form
 *
 * @var $block \Magento\SendFriend\Block\Send
 */
?>
<script id="add-recipient-tmpl" type="text/x-magento-template">
    <div class="actions-toolbar">
        <div class="secondary">
            <button type="button" id="btn-remove<%- data._index_ %>" class="action btn btn-primary btn-lg remove"
               title="<?php /* @escapeNotVerified */ echo $block->escapeJsQuote(__('Remove Recipent')) ?>">
               <span><?php /* @escapeNotVerified */ echo $block->escapeJsQuote(__('Remove')) ?></span>
            </button>
        </div>
    </div>
    <fieldset class="fieldset">
        <div class="field name required">
            <div class="control">
                <input name="recipients[name][<%- data._index_ %>]" placeholder="<?php /* @escapeNotVerified */ echo __('Name') ?> *" type="text" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" class="input-text"
                       id="recipients-name<%- data._index_ %>" data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field email required">
            <div class="control">
                <input name="recipients[email][<%- data._index_ %>]" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?> *" title="<?php /* @escapeNotVerified */ echo __('Email') ?>"
                       id="recipients-email<%- data._index_ %>" type="email" class="input-text"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
    </fieldset>
	<br />
</script>

<form action="<?php /* @escapeNotVerified */ echo $block->getSendUrl() ?>" method="post" id="product-sendtofriend-form"
      data-mage-init='{
        "rowBuilder":{
            "rowTemplate":"#add-recipient-tmpl",
            "rowContainer":"#recipients-options",
            "rowParentElem":"<div></div>",
            "remEventSelector":"button",
            "btnRemoveSelector":".action.remove",
            "maxRows":"<?php /* @escapeNotVerified */ echo $block->getMaxRecipients() ?>",
            "maxRowsMsg":"#max-recipient-message",
            "addRowBtn":"#add-recipient-button",
            "additionalRowClass":"additional"},
        "validation":{}}'
      class="form send friend" data-hasRequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <fieldset class="fieldset sender" id="sender_options">
		<div class="title-inline title-subpage">
			<h3 class="heading full text-uppercase"><span><?php /* @escapeNotVerified */ echo __('Sender') ?></span></h3>
		</div>
        <?php echo $block->getBlockHtml('formkey')?>
        <br>
        <div class="field sender required">
            <div class="control">
                <input name="sender[name]" placeholder="<?php /* @escapeNotVerified */ echo __('Name') ?> *" value="<?php echo $block->escapeHtml($block->getUserName()) ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Name') ?>" id="sender-name" type="text" class="input-text"
                       data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field email required">
            <div class="control">
                <input name="sender[email]" placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?> *" value="<?php echo $block->escapeHtml($block->getEmail()) ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Email') ?>" id="sender-email" type="text" class="input-text"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>

        <div class="field text required">
            <div class="control">
                <textarea name="sender[message]" placeholder="<?php /* @escapeNotVerified */ echo __('Message') ?> *" class="input-text" id="sender-message" cols="3" rows="3"
                          data-validate="{required:true}"><?php echo $block->escapeHtml($block->getMessage()) ?></textarea>
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset recipients">
        <?php echo $block->getBlockHtml('formkey')?>
		<br /><br />
		<div class="title-inline title-subpage">
			<h3 class="heading full text-uppercase"><span><?php /* @escapeNotVerified */ echo __('Invitee') ?></span></h3>
		</div>
        <br />
        <div id="recipients-options"></div>
        <?php if ($block->getMaxRecipients()): ?>
            <div id="max-recipient-message" style="display: none;" class="message notice limit" role="alert">
                <span><?php /* @escapeNotVerified */ echo __('Maximum %1 email addresses allowed.', $block->getMaxRecipients()) ?></span>
            </div>
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="secondary">
            <p><a class="action back" href="#" role="back"><span><?php /* @escapeNotVerified */ echo __('Back') ?></span></a></p>
        </div>
        <div class="primary pull-left">
            <button type="submit"
                    class="action submit btn btn-primary btn-lg primary"<?php if (!$block->canSend()): ?> disabled="disabled"<?php endif ?>>
                <span><?php /* @escapeNotVerified */ echo __('Send Email') ?></span></button>
        </div>
		<div class="secondary pull-right">
			<?php if (1 < $block->getMaxRecipients()): ?>
				<button type="button" id="add-recipient-button" class="action add btn btn-secondary btn-lg">
					<span><?php /* @escapeNotVerified */ echo __('Add Invitee') ?></span></button>
			<?php endif; ?>
		</div>
		<div class="clear"></div>
    </div>
</form>

<script type="text/x-magento-init">
    {
        "a[role='back']": {
            "Magento_SendFriend/back-event": {}
        }
    }
</script>
