<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
	$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
	$themeSettings = $themeHelper->getThemeSettings();
?>
<?php $cats = $_product->getCategoryIds(); ?>
<?php if($themeSettings['product_details']['sku'] || count($cats) > 0): ?>
<div class="product-info-sku">
	<?php if($themeSettings['product_details']['sku']): ?>
	<label class="title"><?php /* @escapeNotVerified */ echo __('SKU') ?>:</label>
	<span class="text-sku"><?php echo $_product->getSku(); ?></span>
	<?php endif ?>
</div>
<?php endif ?>
