<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>
<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <div data-role="loader" class="loading-mask">
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...') ?>">
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "nav": "<?= $block->escapeHtml($block->getVar("gallery/nav")) ?>",
                    <?php if (($block->getVar("gallery/loop"))) : ?>
                        "loop": <?= $block->escapeHtml($block->getVar("gallery/loop")) ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/keyboard"))) : ?>
                        "keyboard": <?= $block->escapeHtml($block->getVar("gallery/keyboard")) ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/arrows"))) : ?>
                        "arrows": <?= $block->escapeHtml($block->getVar("gallery/arrows")) ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/allowfullscreen"))) : ?>
                        "allowfullscreen": <?= $block->escapeHtml($block->getVar("gallery/allowfullscreen")) ?>,
                    <?php endif; ?>
                    <?php if (is_bool($block->getVar("gallery/caption"))) : ?>
                        "showCaption": <?= /* @noEscape */ $block->getVar("gallery/caption") ? 'true' : 'false'; ?>,
                    <?php endif; ?>
                    <?php
    $imgWidth = $block->getImageAttribute('product_page_image_medium', 'width');
    $thumbWidth = $block->getImageAttribute('product_page_image_small', 'width');
    ?>
                        "width": "<?= $block->escapeHtml($imgWidth) ?>",
                        "thumbwidth": "<?= $block->escapeHtml($thumbWidth) ?>",
                    <?php
    $thumbHeight = $block->getImageAttribute('product_page_image_small', 'height')
        ?: $block->getImageAttribute('product_page_image_small', 'width');
    ?>
                    <?php if ($thumbHeight) : ?>
                        "thumbheight": <?= $block->escapeHtml($thumbHeight); ?>,
                    <?php endif; ?>
                    <?php if (($block->getVar("gallery/thumbmargin"))) : ?>
                        "thumbmargin": <?= (int)$block->getVar("gallery/thumbmargin"); ?>,
                    <?php endif; ?>
                    <?php
    $imgHeight = $block->getImageAttribute('product_page_image_medium', 'height')
        ?: $block->getImageAttribute('product_page_image_medium', 'width')
    ?>
                    <?php if ($imgHeight) : ?>
                        "height": <?= $block->escapeHtml($imgHeight); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/transition/duration")) : ?>
                        "transitionduration": <?= $block->escapeHtml($block->getVar("gallery/transition/duration")) ?>,
                    <?php endif; ?>
                    "transition": "<?= $block->escapeHtml($block->getVar("gallery/transition/effect")) ?>",
                    <?php if (($block->getVar("gallery/navarrows"))) : ?>
                        "navarrows": <?= $block->escapeHtml($block->getVar("gallery/navarrows")) ?>,
                    <?php endif; ?>
                    "navtype": "<?= $block->escapeHtml($block->getVar("gallery/navtype")) ?>",
                    "navdir": "<?= $block->escapeHtml($block->getVar("gallery/navdir")) ?>"
                },
                "fullscreen": {
                    "nav": "<?= $block->escapeHtml($block->getVar("gallery/fullscreen/nav")) ?>",
                    <?php if ($block->getVar("gallery/fullscreen/loop")) : ?>
                        "loop": <?= $block->escapeHtml($block->getVar("gallery/fullscreen/loop")) ?>,
                    <?php endif; ?>
                    "navdir": "<?= $block->escapeHtml($block->getVar("gallery/fullscreen/navdir")) ?>",
                    <?php if ($block->getVar("gallery/transition/navarrows")) : ?>
                        "navarrows": <?= $block->escapeHtml($block->getVar("gallery/fullscreen/navarrows")) ?>,
                    <?php endif; ?>
                    "navtype": "<?= $block->escapeHtml($block->getVar("gallery/fullscreen/navtype")) ?>",
                    <?php if ($block->getVar("gallery/fullscreen/arrows")) : ?>
                        "arrows": <?= $block->escapeHtml($block->getVar("gallery/fullscreen/arrows")) ?>,
                    <?php endif; ?>
                    <?php if (is_bool($block->getVar("gallery/fullscreen/caption"))) : ?>
        <?php $showCaption = $block->getVar("gallery/fullscreen/caption") ? 'true' : 'false'; ?>
                        "showCaption": <?= /* @noEscape */ $showCaption ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")) : ?>
                        "transitionduration": <?=
        $block->escapeHtml($block->getVar("gallery/fullscreen/transition/duration")) ?>,
                    <?php endif; ?>
                    "transition": "<?= $block->escapeHtml($block->getVar("gallery/fullscreen/transition/effect")) ?>"
                },
                "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
