<?php $helper = $this->helper('MGS\Social\Helper\Data'); ?>
<?php if ($helper->getConfig('facebook_settings/active')): ?>
    <?php
    require_once BP . '/app/code/MGS/Social/lib/facebook/src/facebook.php';
    $appId = $helper->getConfig('facebook_settings/client_id');
    $appSecret = $helper->getConfig('facebook_settings/client_secret');
    $returnUrl = $helper->getUrl('social/facebook/connect');
    $fbPermissions = 'email';
    $facebook = new \Facebook(array(
        'appId' => $appId,
        'secret' => $appSecret

    ));
    $fbUser = $facebook->getUser();
    ?>
    <?php if (!$fbUser || !$helper->checkLoggedIn()): ?>
        <?php
        $fbUser = null;
        $loginUrl = $facebook->getLoginUrl(array('redirect_uri' => $returnUrl, 'scope' => $fbPermissions));
        ?>
        <div class="social-facebook">
            <a class="facebook" title="<?php echo __('Login with Facebook'); ?>" href="#" onclick="socialLogin('<?php echo $loginUrl; ?>'); return false;"><span class="icon fa fa-facebook"></span></a>
        </div>
    <?php endif; ?>
<?php endif; ?>