<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter">
        <div class="block-content filter-content">
			<?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <!--<div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ //echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ //echo __('Clear All') ?></span></a>
                </div>-->
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if (!$wrapOptions): ?>
                    <div class="filter-options" id="narrow-by-list">
                <?php $wrapOptions = true; endif; ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <div class="panel panel-primary block filter-options-block">
							<div role="heading" aria-level="3" class="panel-heading  block-title"><h4 class="title"><span><?php echo $block->escapeHtml(__($filter->getName())) ?></span></h4></div>
							<div class="panel-body"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
						</div>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
