<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $_product = $block->getProduct() ?>
<?php if ($_product->isSaleable() && $block->hasOptions()):?>
    <div class="bundle-actions">
        <button id="bundle-slide"
                class="action primary btn btn-primary btn-lg customize"
                type="button">
            <span><?php /* @escapeNotVerified */ echo __('Customize and Add to Cart'); ?> <i class="fa fa-sort-desc"></i></span>
        </button>
    </div>
<?php endif;?>
