<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Review\Block\Form
 */
?>
<div class="block review-add">
<div class="title-inline">
	<h3 class="heading full text-uppercase"><?php /* @escapeNotVerified */ echo __('Write Your Own Review') ?></h3>
</div>
<div class="block-content">
<?php if ($block->getAllowWriteReviewFlag()): ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <?php echo $block->getChildHtml('form_fields_before')?>
    <div class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
        <legend class="legend review-legend"><span><?php /* @escapeNotVerified */ echo __("You're reviewing:"); ?></span><strong><?php echo $block->escapeHtml($block->getProductInfo()->getName()) ?></strong></legend>
        <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
        <span id="input-message-box"></span>
        <div class="field required review-field-ratings">
			<div class="title-inline" style="margin-bottom: 15px;">
				<h5 class="heading full"><?php /* @escapeNotVerified */ echo __('Your Rating') ?> *</h5>
			</div>
            <div class="control">
                <div class="nested" id="product-review-table">
					<div class="field choice review-field-rating">
						<div class="control review-control-vote">
							<div class="table-responsive">
								<table class="add-review-table">
									<thead>
										<tr>
											<th></th>
											<th><?php /* @escapeNotVerified */ echo __('1 star') ?></th>
											<th><?php /* @escapeNotVerified */ echo __('2 star') ?></th>
											<th><?php /* @escapeNotVerified */ echo __('3 star') ?></th>
											<th><?php /* @escapeNotVerified */ echo __('4 star') ?></th>
											<th><?php /* @escapeNotVerified */ echo __('5 star') ?></th>
										</tr>
									</thead>
									<tbody>
										<?php foreach ($block->getRatings() as $_rating): ?>
										<tr>
											<th><span id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?php echo $block->escapeHtml($_rating->getRatingCode()) ?></span></span></th>
											<?php $options = $_rating->getOptions();?>
											<?php $iterator = 1; foreach ($options as $_option): ?>
												<td><input
													type="radio"
													name="ratings[<?php /* @escapeNotVerified */ echo $_rating->getId() ?>]"
													id="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>"
													value="<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
													class="radio"
													data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
													aria-labelledby="<?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?php echo $block->escapeHtml($_rating->getRatingCode()) ?>_<?php /* @escapeNotVerified */ echo $_option->getValue() ?>_label" /></td>
											<?php $iterator++; ?>
											<?php endforeach; ?>
										</tr>
										<?php endforeach; ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
                </div>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
            </div>
        </div>
    <?php endif ?>
        <div class="field review-field-nickname required">
            <div class="control">
                <input type="text" name="nickname" id="nickname_field" placeholder="<?php /* @escapeNotVerified */ echo __('Nickname') ?> *" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
            </div>
        </div>
        <div class="field review-field-summary required">
            <div class="control">
                <input type="text" name="title" id="summary_field" placeholder="<?php /* @escapeNotVerified */ echo __('Summary') ?> *" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
            </div>
        </div>
        <div class="field review-field-text required">
            <div class="control">
                <textarea name="detail" class="form-control" id="review_field" cols="5" placeholder="<?php /* @escapeNotVerified */ echo __('Review') ?> *" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
            </div>
        </div>
    </div>
    <div class="actions-toolbar review-form-actions">
        <div class="primary actions-primary">
            <button type="submit" class="action submit primary btn btn-lg btn-primary"><span><?php /* @escapeNotVerified */ echo __('Submit Review') ?></span></button>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {}
    }
}
</script>
<?php else: ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?php /* @escapeNotVerified */ echo __('Only registered users can write reviews. Please, <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
        </div>
    </div>
<?php endif ?>
</div>
</div>
