<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="header-newsletter switcher " id="header-newsletter">
	<span class="name" data-mage-init='{"dropdown":{}}' data-toggle="dropdown">
            <span class="action"><i class="fa fa-envelope-o"></i><span class="hidden-sm hidden-xs"><?php echo __('Newsletter Singup')?></span></span>
	</span>
	<div class="content dropdown switcher-dropdown" style="display:none;" data-target="dropdown" data-mage-init='{"dropdownDialog":{
            "appendTo":"#header-newsletter",
            "triggerTarget":"#header-newsletter > .name",
            "closeOnMouseLeave": false,
            "triggerClass":"active",
            "parentClass":"active",
            "defaultDialogClass":"dropdown-menu",
            "buttons":null}}'>
	<form class="form subscribe"
		novalidate
		action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
		method="post"
		data-mage-init='{"validation": {"errorClass": "mage-error"}}'
		id="header-newsletter-validate-detail">
		<div class="field newsletter">			
			<div class="control">
				<input class="input-text" name="email" type="email" id="newsletter-head"
							placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
							data-validate="{required:true, 'validate-email':true}"/>
			</div>
		</div>
		<div class="actions">
			<button class="action subscribe primary btn btn-primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                            <span><i class="fa fa-envelope-o"></i></span>
			</button>
		</div>
	</form>
</div>
</div>

