<?php $portfolios = $this->getPortfolios() ?>
<?php $menu = $this->getMenu();
    
?>
<?php if($this->getRequest()->getParam('id')){
	$checkParam = true;
	$id_param = $this->getRequest()->getParam('id');
}else{
	$checkParam = false;
}
?>

<div class="tabs-categories-portfolio-content isotope row">
    <?php if(count($portfolios)>0): ?>
    <div class="portfolio-gird">
        <?php foreach($portfolios as $portfolio): ?>
        <div class="item item_all col-md-4 col-sm-6 col-xs-12">
            <div class="portfolio-content">
                <div class="portfolio-top-content">
                    <?php $thumbnailUrl = $this->getThumbnailSrc($portfolio) ?>
                    <?php $portfolioUrl = $this->getPortfolioAddress($portfolio) ?>
                    <?php if($thumbnailUrl): ?>
                    <a class="portfolio-image" href="<?php echo $portfolioUrl;?>"><img src="<?php echo $thumbnailUrl;?>" alt="" class="img-responsive"/></a>
                    <?php endif;?>
                    <a class="view" href="<?php echo $portfolioUrl; ?>">
                                                    <span class="hover-info">
							<span class="fa fa-search"></span>
						</span>
                                                </a>
                </div>
                <div class="portfolio-bottom-content">
                    <h5 class="portfolio-name text-uppercase">
                        <a href="<?php echo $portfolioUrl;?>"><?php echo $portfolio->getName();?></a>
                    </h5>
                    <p class="category-link text-desc"><?php echo $this->getCategoriesLink($portfolio)?></p>
                </div>
            </div>
            
        </div>
        <?php endforeach;?>
        
    </div>
    <?php else:?>
        <div class="alert alert-danger item col-xs-12 item_all" style="min-height: 40px;"><?php echo __('There are no portfolios matching the selection.') ?></div>
    <?php endif;?>

</div>