<?php $portfolio = $this->getPortfolio() ?>
<div class="row portfolio-details">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="portfolio-image">
			<img src="<?php echo $this->getBaseImage($portfolio)?>" alt="" class="img-responsive"/>
		</div>
	</div>
    <div class="col-md-12 col-xs-12 col-sm-12">
        <h2 class="text-upprecase title-portfolio"><?php echo $portfolio->getName() ?></h2>
        <p class="text-desc portfolio-category"><?php echo $this->getCategoriesLink($portfolio)?></p>
    </div>
    <div class="col-md-9 col-sm-12 col-xs-12">
        <div class="description"><?php echo nl2br($portfolio->getDescription()) ?></div>
    </div>
    
    
	<div class="col-md-3 col-sm-12 col-xs-12">
		<div class="portfolio-content">		
			
			<table class="table portfolio-table">
				<tbody>
					<?php $date = $portfolio->getPortfolioDate() ?>
					<?php if($date != ''): ?>
						<tr>
							<td><?php echo __('Date:') ?></td>
							<td class="text-desc"><?php echo date('F d, Y', strtotime($date))?></td>
						</tr>
					<?php endif ?>
					
                                        <?php $categoryLinks = $this->getCategoriesLink($portfolio) ?>
					<?php if($categoryLinks != ''): ?>
						<tr>
							<td><?php echo __('Categories:') ?></td>
							<td class="text-desc"><?php echo $categoryLinks ?></td>
						</tr>
					<?php endif ?>
                                                
                                                
					<?php $service = $portfolio->getServices() ?>
					<?php if($service != ''): ?>
						<tr>
							<td><?php echo __('Project:') ?></td>
							<td class="text-desc"><?php echo $service ?></td>
						</tr>
					<?php endif ?>
					
					<?php $client = $portfolio->getClient() ?>
					<?php if($client != ''): ?>
						<tr>
							<td><?php echo __('Client:') ?></td>
							<td class="text-desc"><?php echo $client ?></td>
						</tr>
					<?php endif ?>
					
					<?php $skills = $portfolio->getSkills() ?>
					<?php if($skills != ''): ?>
						<tr>
							<td><?php echo __('Skills:') ?></td>
							<td class="text-desc"><?php echo $skills ?></td>
						</tr>
					<?php endif ?>
					
				</tbody>
			</table>
                    <?php if($portfolio->getProjectUrl() !=''): ?>
                    <a class="btn btn-default btn-lg btn-full" target="_blank" href="<?php echo $portfolio->getProjectUrl() ?>"><?php echo __('View Project')?></a>
                    <?php endif;?>
		</div>
	</div>
	
	<?php $relatedPortfolio = $this->getRelatedPortfolio($portfolio) ?>
	<?php if(count($relatedPortfolio)>0): ?>
		<div class="portfolio-container col-md-12 col-sm-12 col-xs-12">
			<div class="block-title title-inline" style="margin-bottom:30px;">
                            <h3 class="heading full text-uppercase"><span><?php echo __('Related Works') ?></span></h3>
			</div>
                    <div class="row">
			<div class="owl-carousel portfolio-carousel" id="portfolio_carousel">
			<?php foreach($relatedPortfolio as $_portfolio): ?>
				<div class="item">
                                    <div class="portfolio-content">
                                        <?php $address = $this->getPortfolioAddress($_portfolio) ?>
					<div class="portfolio-top-content">
						<a href="<?php echo $address; ?>" class="portfolio-image"><img src="<?php echo $this->getThumbnailSrc($_portfolio)?>" alt="" class="img-responsive"/></a>
                                                <a class="view" href="<?php echo $address; ?>">
                                                    <span class="hover-info">
							<span class="fa fa-search"></span>
						</span>
                                                </a>
                                                
					</div>
					<div class="portfolio-bottom-content">
                                            <h5 class="portfolio-name text-uppercase"><a href="<?php echo $address; ?>"><?php echo $_portfolio->getName() ?></a></h5>
						<p class="category-link text-desc"><?php echo $this->getCategoriesLink($_portfolio)?></p>
					</div>
                                        
                                    </div>					
				</div>
			<?php endforeach ?>
			</div>
                    </div>
		</div>
		
		<script type="text/javascript">
			require([
				'jquery',
				'mgs/owlcarousel'
			], function(jQuery){
				(function($) {
					$("#portfolio_carousel").owlCarousel({
						items: 4,
						nav: true,
						dots: false,
						autoplay: false,
                                                navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
						margin: 30,
						responsive:{
							0 : {items: 1},
							480 : {items: 1},
							768 : {items: 2},
							980 : {items: 4},
							1200 : {items: 4}
						}
					});
				})(jQuery);
			});
		</script>
	<?php endif ?>
</div>